# Use the official PHP image as the base image
FROM php:latest
# Copy the PHP app files to the container
COPY index.php /var/www/html
COPY db.php /var/www/html
# Expose port 80 for web traffic
# Set the working directory
