services:
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    depends_on:
      - create
      - delete
      - index
      - update

  create:
    build: ./create
    ports:
      - "30081:80"

  delete:
    build: ./delete
    ports:
      - "30082:80"

  index:
    build: ./index
    ports:
      - "30083:80"

  update:
    build: ./update
    ports:
      - "30084:80"
