apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete
  template:
    metadata:
      labels:
        app: delete
    spec:
      containers:
      - name: delete
        image: javierlim05/delete:latest
        ports:
        - containerPort: 80
          imagePullPolicy: Always
