apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: create
        image: javierlim05/index:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
