apiVersion: apps/v1
kind: Deployment
metadata:
  name: update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update
  template:
    metadata:
      labels:
        app: update
    spec:
      containers:
      - name: update
        image: javierlim05/update:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
